servers:
  web:
    hosts:
      - dev.slovensko.digital
  worker:
    hosts:
      - dev.slovensko.digital

x-load-env:
  - "<% require 'dotenv'; Dotenv.load('.env.staging') %>"

env:
  clear:
    GOOD_JOB_MAX_THREADS: 10
    RAILS_ENV: production
    ROLLBAR_ENV: dev
    APP_HOST: ops.dev.slovensko.digital
    LEGACY_PORTAL_URL: https://www.odkazprestarostu.sk
    CONNECTOR__OPS_API_URL: https://ops.dev.slovensko.digital/
    CONNECTOR_WEBHOOK_URL: https://ops.dev.slovensko.digital/connector/webhook
    CMS_ROOT_CATEGORY_ID: 15
    CMS_AI_CATEGORY_ID: 18
    TRIAGE_ZAMMAD_URL: https://triage.ops.dev.slovensko.digital/
    NOTIFICATION_SMTP_USERNAME: notifikacie@ops.dev.slovensko.digital
    NOTIFICATION_SMTP_SERVER: smtp.m1.websupport.sk
    NOTIFICATION_SMTP_PORT: 587
    DISCOURSE_URL: https://forum.odkazprestarostu.sk/
    DISCOURSE_IMPORT_CATEGORY_IDS: "15,18"
    AWS_S3_BUCKET: portal-ops-dev-storage
    AWS_S3_REGION: eu-central-1
    AWS_REGION: eu-central-1

proxy:
  host: ops.dev.slovensko.digital

volumes:
  - "ops_portal_storage:/rails/storage"

ssh:
  user: kamal
