servers:
  web:
    hosts:
      - 195.201.202.110
  worker:
    hosts:
      - 195.201.202.110

env:
  clear:
    WEB_CONCURRENCY: 4
    RAILS_MAX_THREADS: 5
    GOOD_JOB_MAX_THREADS: 20
    RAILS_ENV: production
    ROLLBAR_ENV: production
    APP_HOST: novy.odkazprestarostu.sk
    LEGACY_PORTAL_URL: https://www.odkazprestarostu.sk
    CONNECTOR__OPS_API_URL: https://novy.odkazprestarostu.sk/
    CONNECTOR_WEBHOOK_URL: https://novy.odkazprestarostu.sk/connector/webhook
    CMS_ROOT_CATEGORY_ID: 15
    CMS_AI_CATEGORY_ID: 18
    TRIAGE_ZAMMAD_URL: https://triaz.odkazprestarostu.sk/
    NOTIFICATION_SMTP_USERNAME: notifikacie@odkazprestarostu.sk
    NOTIFICATION_SMTP_SERVER: smtp.m1.websupport.sk
    NOTIFICATION_SMTP_PORT: 587
    DISCOURSE_URL: https://forum.odkazprestarostu.sk/
    DISCOURSE_IMPORT_CATEGORY_IDS: "15,18"
    AWS_S3_BUCKET: ops-prod-portal-storage
    AWS_S3_REGION: eu-central-1
    AWS_REGION: eu-central-1
    EMAILS_IMPORT: "ON"
    AUTO_SYNC_LEGACY_USERS: "ON"
    TRIAGE_ZAMMAD_TECH_USER_ID: 5

proxy:
  host: novy.odkazprestarostu.sk

volumes:
  - "ops_portal_storage:/rails/storage"

accessories:
  nginx:
    image: nginx:alpine
    hosts:
      - 195.201.202.110
    proxy:
      hosts:
        - www.odkazprestarostu.sk
        - odkazprestarostu.sk
      ssl: true
      app_port: 80
      forward_headers: true
    files:
      - config/nginx_redirects.conf:/etc/nginx/conf.d/default.conf:ro

ssh:
  user: kamal
