service: ops-portal

image: sd/ops-portal

servers:
  web:
    options:
      "add-host": host.docker.internal:host-gateway
  worker:
    cmd: bundle exec good_job start
    options:
      "add-host": host.docker.internal:host-gateway

# TODO temporary
deploy_timeout: 200

proxy:
  ssl: true
  app_port: 3000

env:
  secret:
    - SECRET_KEY_BASE
    - DATABASE_URL
    - ANTHROPIC_API_KEY
    - GEMINI_API_KEY
    - TRIAGE_ZAMMAD_API_TOKEN
    - TRIAGE_ZAMMAD_WEBHOOK_SECRET
    - LEGACY_DB_URL
    - GOOGLE_CLIENT_ID
    - GOOGLE_CLIENT_SECRET
    - FACEBOOK_APP_ID
    - FACEBOOK_APP_SECRET
    - NOTIFICATION_SMTP_PASSWORD
    - DISCOURSE_API_KEY
    - DISCOURSE_WEBHOOK_SECRET
    - AWS_S3_ACCESS_KEY_ID
    - AWS_S3_SECRET_ACCESS_KEY
    - AWS_S3_BUCKET
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_REGION
    - ROLLBAR_ACCESS_TOKEN
    - ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY
    - ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY
    - ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT

  clear:
    GOOD_JOB_EXECUTION_MODE: external

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

registry:
  server: registry.dev.slovensko.digital
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  remote: ssh://kamal@dev.slovensko.digital
  cache:
    type: registry
    options: mode=max,image-manifest=true,oci-mediatypes=true

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
#
# asset_path: /app/public/assets

# Configure rolling deploys by setting a wait time between batches of restarts.
#
# boot:
#   limit: 10 # Can also specify as a percentage of total hosts, such as "25%"
#   wait: 2
