server {
    listen 80;
    server_name www.odkazprestarostu.sk odkazprestarostu.sk;

    location ~ ^/(login|ludia|vsetky-podnety|malacky|stupava|levice|martin|dolne-vestenice|stara-tura|lozorno|senica|handlova|komarno|jarok|puchov|vranov-nad-toplou|zazriva|ivanka-pri-dunaji|lucenec|holic|cifer|nova-bana|spisske-tomasovce|hlohovec|modra|sabinov|banska-bystrica|pezinok|trnava|dolny-kubin|dubnica-nad-vahom|prievidza|nitra|aleksince|batovce|bucany|dubnik|horna-suca|jablonica|janova-lehota|krizovany-nad-dudvahom|lendak|myjava|nalepkovo|namestovo|ochodnica|rajec|rozkovany|semerovo|spisska-nova-ves|studienka|trencianske-bohuslavice|trstena|trstene-pri-hornade|turany|turna-nad-bodvou|turzovka|velka-ida|velke-ulany|bosaca|bojnice|banov|banovce-nad-bebravou|bystricany|cerveny-klastor|dolny-lopasov|drahovce|durcina|dvory-nad-zitavou|hlboke-nad-vahom|hontianske-nemce|chmelnica|jesenske|kostoliste|koseca|koskovce|krasno-nad-kysucou|levoca|liptovsky-hradok|malachov|mytna|nizny-hrusov|nova-ves-nad-zitavou|ostrov|pecovska-nova-ves|piestany|plastovce|podhajska|prievaly|rajecke-teplice|rimavska-bana|secovce|svidnik|stitnik|teplicka|tesedikovo|valaska|vysoke-tatry|vysna-mysla|vysna-sebastova|zakamenne|zvolen|ziar-nad-hronom|zikava|zemianske-kostolany|liptovsky-mikulas|biely-kostol|brezova-pod-bradlom|letanovce|bratislava|abc|babin|borsky-svaty-jur|bystricka|cadca|cervenik|cierny-balog|dobsina|hamuliakovo|hnusta|horna-dolna|horovce|humenne|hviezdoslavov|istebne|jablonov-nad-turnou|jasenie|kezmarok|klastor-pod-znievom|kosice|lietavska-lucka|medzev|moldava-n-bodvou|moravany-nad-vahom|nove-mesto-nad-vahom|nove-zamky|ostry-grun|plave-vozokany|poprad|povazska-bystrica|presov|rozhanovce|senec|skalica|sliac|smolenice|snina|stara-lubovna|stropkov|sulov-hradna|svaty-jur|sala|samorin|trebisov|trencin|vinodol|vinosady|vlkanova|vysna-jedlova|zavar|zelenec|zlate-moravce|zohor|zeliezovce|zilina)(/.*)?$ {
        return 301 https://novy.odkazprestarostu.sk/r/$1$2;
    }

    location ~ ^/?$ {
        return 301 https://novy.odkazprestarostu.sk/;
    }

    location / {
        return 301 https://novy.odkazprestarostu.sk/r$request_uri;
    }
}

server {
    listen 80;
    server_name api.odkazprestarostu.sk;

    return 404;
}

server {
    listen 80;
    server_name samospravy.odkazprestarostu.sk;

    return 301 https://novy.odkazprestarostu.sk/;
}

server {
    listen 80;

    location = /up {
        access_log off;
        return 200 "OK";
        add_header Content-Type text/plain;
    }
}
