name: Deploy to DEV

on:
  workflow_call:
  workflow_dispatch:

jobs:
  dev-deploy:
    name: Deploy to DEV environment
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install Kamal gem
        run: |
          KAMAL_VERSION=$(ruby -rbundler -e "puts Bundler.locked_gems.specs.find { |s| s.name == 'kamal' }&.version")
          gem install kamal -v $KAMAL_VERSION

      - uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.DEV_DEPLOY_KEY }}

      - name: Run deploy command
        env:
          KAMAL_REGISTRY_USERNAME: ${{ secrets.KAMAL_REGISTRY_USERNAME }}
          KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          LEGACY_DB_URL: ${{ secrets.LEGACY_DB_URL }}
          SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
          TRIAGE_ZAMMAD_API_TOKEN: ${{ secrets.TRIAGE_ZAMMAD_API_TOKEN }}
          TRIAGE_ZAMMAD_WEBHOOK_SECRET: ${{ secrets.TRIAGE_ZAMMAD_WEBHOOK_SECRET }}
          LEGACY_PORTAL_URL: ${{ vars.LEGACY_PORTAL_URL }}
          CONNECTOR__OPS_API_URL: ${{ vars.CONNECTOR__OPS_API_URL }}
          CONNECTOR_WEBHOOK_URL: ${{ vars.CONNECTOR_WEBHOOK_URL }}
          TRIAGE_ZAMMAD_URL: ${{ vars.TRIAGE_ZAMMAD_URL }}
          FACEBOOK_APP_ID: ${{ vars.FACEBOOK_APP_ID }}
          FACEBOOK_APP_SECRET: ${{ secrets.FACEBOOK_APP_SECRET }}
          GOOGLE_CLIENT_ID: ${{ vars.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          CMS_ROOT_CATEGORY_ID: ${{ vars.CMS_ROOT_CATEGORY_ID }}
          CMS_AI_CATEGORY_ID: ${{ vars.CMS_AI_CATEGORY_ID }}
          NOTIFICATION_SMTP_USERNAME: ${{ vars.NOTIFICATION_SMTP_USERNAME }}
          NOTIFICATION_SMTP_SERVER: ${{ vars.NOTIFICATION_SMTP_SERVER }}
          NOTIFICATION_SMTP_PORT: ${{ vars.NOTIFICATION_SMTP_PORT }}
          NOTIFICATION_SMTP_PASSWORD: ${{ secrets.NOTIFICATION_SMTP_PASSWORD }}
          DISCOURSE_API_KEY: ${{ secrets.DISCOURSE_API_KEY }}
          DISCOURSE_WEBHOOK_SECRET: ${{ secrets.DISCOURSE_WEBHOOK_SECRET }}
          DISCOURSE_URL: ${{ vars.DISCOURSE_URL }}
          DISCOURSE_API_USERNAME: ${{ vars.DISCOURSE_API_USERNAME }}
          DISCOURSE_IMPORT_CATEGORY_IDS: ${{ vars.DISCOURSE_IMPORT_CATEGORY_IDS }}
          AWS_S3_REGION: ${{ vars.AWS_S3_REGION }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_S3_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_S3_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
          ADMIN_EMAILS: ${{ vars.ADMIN_EMAILS }}
          MAINTENANCE: ${{ vars.MAINTENANCE }}

        run: kamal deploy -d staging
